version: '3.9'
services:
  frontend:
    build:
      context: ../frontend
    container_name: godakpin-frontend
    ports:
      - '3005:3000'
    env_file:
      - ../frontend/.env.production
    restart: unless-stopped
    networks:
      - godakpin-net

  backend:
    build:
      context: ../backend
    container_name: godakpin-backend
    ports:
      - '4005:4000'
    env_file:
      - ../backend/.env.production
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - godakpin-net

  mongo:
    image: mongo:6
    container_name: godakpin-db
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - '27025:27017'
    networks:
      - godakpin-net

networks:
  godakpin-net:
    driver: bridge

volumes:
  mongo-data:
